defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:8.11.2-stretch

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
     
      - run:
          name: workaround for node-gyp
          command: rm -rf ~/.node-gyp

      - run:
          name: install gitbook CLI
          command: npm uninstall -g gitbook && npm install

      - run:
          name: gitbook install
          command: npx gitbook install

      - run:
          name: gitbook build
          command: npx gitbook build
    
  build_and_deploy:
    <<: *defaults
    steps:
      - checkout

      - add_ssh_keys:
          fingerprints:
            - "6c:17:37:96:90:a8:37:2c:3f:69:95:7e:1e:a6:92:04"
     
      - run:
          name: workaround for node-gyp
          command: rm -rf ~/.node-gyp

      - run:
          name: install gitbook CLI
          command: npm uninstall -g gitbook && npm install

      - run:
          name: gitbook install
          command: npx gitbook install

      - run:
          name: gitbook build
          command: npx gitbook build
      
      - run: 
          name: setup github email
          command: git config --global user.email $GH_EMAIL
      
      - run: 
          name: setup github name
          command: git config --global user.name $GH_NAME
      - run:
          name: deploy github pages
          command: npx gh-pages -d _book

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              ignore: 
                - gh-pages
                - master
      - build_and_deploy:
          filters:
            branches:
              only: master
