defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:8.11.2-stretch

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout

      - run:
          name: install gitbook CLI
          command: npm uninstall -g gitbook && npm install

      - run:
          name: gitbook install
          command: npx gitbook install

      - run:
          name: gitbook build
          command: npx gitbook build
    
  build_and_deploy:
    <<: *defaults
    steps:
      - checkout

      - add_ssh_keys:
          fingerprints:
            - "6c:17:37:96:90:a8:37:2c:3f:69:95:7e:1e:a6:92:04"

      - run:
          name: install gitbook CLI
          command: npm uninstall -g gitbook && npm install

      - run:
          name: gitbook install
          command: npx gitbook install

      - run:
          name: gitbook build
          command: npx gitbook build
      
      - run:
          name: deploy heroku
          command: git push https://heroku:${HEROKU_API_KEY}@git.heroku.com/${HEROKU_APP_NAME}.git ${CIRCLE_BRANCH}:master

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              ignore: 
                - gh-pages
                - migrate_to_heroku
                - master
      - build_and_deploy:
          filters:
            branches:
              only: 
                - master
                - migrate_to_heroku
