defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:latest

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
     
      - run:
          name: install gitbook CLI
          command: npm uninstall -g gitbook && npm install

      - run:
          name: gitbook install
          command: npx gitbook install

      - run:
          name: gitbook build
          command: npx gitbook build
    
  deploy:
    <<: *defaults
    steps:
      - add_ssh_keys:
          fingerprints:
            - "6c:17:37:96:90:a8:37:2c:3f:69:95:7e:1e:a6:92:04"

      - run:
          name: deploy github pages
          command: npx ghpages -p _book

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              ignore: gh-pages
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
