---
# _______  ______    _______  ______   __   __  _______  _______  ___   _______  __    _
# |       ||    _ |  |       ||      | |  | |  ||       ||       ||   | |       ||  |  | |
# |    _  ||   | ||  |   _   ||  _    ||  | |  ||       ||_     _||   | |   _   ||   |_| |
# |   |_| ||   |_||_ |  | |  || | |   ||  |_|  ||       |  |   |  |   | |  | |  ||       |
# |    ___||    __  ||  |_|  || |_|   ||       ||      _|  |   |  |   | |  |_|  ||  _    |
# |   |    |   |  | ||       ||       ||       ||     |_   |   |  |   | |       || | |   |
# |___|    |___|  |_||_______||______| |_______||_______|  |___|  |___| |_______||_|  |__|
#
# Customer facing documentation - handle with care!
# List of RELEASES Docs packages.
#

  -
    title: "EPG Ingestion"
    kit: "CONTENT-KIT"
    relativeURL: "epg-ingestion"
    package: "https://token@github.com/applicaster/applicaster2.git#master"
    glob: "./doc/features/epg-ingestion.md"
  -
    title: "Authorization Provider"
    kit: "PLATFORM-KIT"
    relativeURL: "authorization-provider"
    package: "https://token@github.com/applicaster/applicaster2.git#6fe6d4350e"
    glob: "./doc/features/authorization_provider/**"
  -
    title: "JS2Native v1.1.0"
    kit: "PLATFORM-KIT"
    relativeURL: "js2native"
    package: "https://token@github.com/applicaster/js2native.git"
    glob: "./docs/readme.md"
  -
    title: "iOS Feed Integration"
    kit: "GAME-KIT"
    relativeURL: "ios-feed-integration"
    package: "https://token@github.com/applicaster/Applicaster-iOS-SDK-Lite-Static.wiki.git"
    glob: "./Feed-integration-instructions.md"
  -
    title: "iOS CrossMates Integration"
    kit: "GAME-KIT"
    relativeURL: "ios-crossmates-integration"
    package: "https://token@github.com/applicaster/Applicaster-iOS-SDK-Lite-Static.wiki.git"
    glob: "./Crossmates-integration-instructions.md" 
  -
    title: "Android Feed Integration"
    kit: "GAME-KIT"
    relativeURL: "android-feed-integration"
    package: "https://token@github.com/applicaster/feed_android.git"
    glob: "./README.md"
  -
    title: "Android CrossMates Integration"
    kit: "GAME-KIT"
    relativeURL: "android-crossmates-integration"
    package: "https://token@github.com/applicaster/Crossmates-Demo-Android.git"
    glob: "./README.md"
  -
    title: "Android Applicaster SDK Integration"
    kit: "GAME-KIT"
    relativeURL: "android-applicaster-sdk-integration"
    package: "https://token@github.com/applicaster/applicaster-android-sdk.git"
    glob: "./README.md"
  -
    title: "Media Atom v1.2.0"
    kit: "CONTENT-KIT"
    relativeURL: "media-atom"
    package: "https://token@github.com/applicaster/applicaster-developer-documentation.git"
    glob: "./src/content/**"
  -
    title: "On Screen Graphics Reports Export"
    kit: "GAME-KIT"
    relativeURL: "on-screen-graphics-reports"
    package: "https://token@github.com/applicaster/applicaster-widgets.git#OSG-fix-docs-folder-structure"
    glob: "./doc/features/on_screen_graphics_reports_export/**"
  -
    title: "Stars Public API v3"
    kit: "GAME-KIT"
    relativeURL: "stars-public-v3"
    package: "https://token@github.com/applicaster/stars.git#add-feed3-features"
    glob: "./doc/**"
  -
    title: "VOD Ingestion via RSS"
    kit: "PLATFORM-KIT"
    relativeURL: "vod-ingestion-rss"
    package: "https://token@github.com/applicaster/vod-rss-media-documentation.git"
    glob: "./RSSVODIngestion.md"
  -
    title: "VOD ingestion via XML"
    kit: "PLATFORM-KIT"
    relativeURL: "vod-ingestion-xml"
    package: "https://token@github.com/applicaster/applicaster2.git#master"
    glob: "./doc/features/ingestion/vod_via_xml.md"
