---
# List of INTERNAL Docs packages
  -
    title: "Developer Documentation"
    kit: "PLATFORM-KIT"
    relativeURL: "dev-doc-readme"
    package: "../docs/"
    glob: "./**"
  -
    title: "Question Service"
    kit: "GAME-KIT"
    relativeURL: "question-service"
    package: "../content/question-service/"
    glob: "./**"
