---
# List of INTERNAL Docs packages
  -
    title: "atom-enhancements PR"
    kit: "CONTENT-KIT"
    relativeURL: "atom-next-release"
    package: "https://token@github.com/applicaster/applicaster-developer-documentation.git#move-md-files"
    glob: "./src/content/**"
    commetsURL: "https://github.com/applicaster/applicaster-developer-documentation/pull/11"
    notes:
      ATOM enhencments draft. includes notations
      about "updated", "summery", "author name"
      and "alternate link" elements
  -
    title: "Developer Documentation"
    kit: "PLATFORM-KIT"
    relativeURL: "dev-doc-readme"
    package: "../docs/"
    glob: "./**"
  -
    title: "iOS Feed Integration"
    kit: "PLATFORM-KIT"
    relativeURL: "ios-feed-integration"
    package: "https://token@github.com/applicaster/Applicaster-iOS-SDK-Lite-Static.wiki.git"
    glob: "./Feed-integration-instructions.md"
  -
    title: "Question Service"
    kit: "GAME-KIT"
    relativeURL: "question-service"
    package: "../content/question-service/"
    glob: "./**"
