---
# _______  ______    _______  ______   __   __  _______  _______  ___   _______  __    _
# |       ||    _ |  |       ||      | |  | |  ||       ||       ||   | |       ||  |  | |
# |    _  ||   | ||  |   _   ||  _    ||  | |  ||       ||_     _||   | |   _   ||   |_| |
# |   |_| ||   |_||_ |  | |  || | |   ||  |_|  ||       |  |   |  |   | |  | |  ||       |
# |    ___||    __  ||  |_|  || |_|   ||       ||      _|  |   |  |   | |  |_|  ||  _    |
# |   |    |   |  | ||       ||       ||       ||     |_   |   |  |   | |       || | |   |
# |___|    |___|  |_||_______||______| |_______||_______|  |___|  |___| |_______||_|  |__|
#
# Cutomrt facing handle with care.
# List of RELEASES Docs packages.
#
  -
    title: "Media Atom v1.1.0"
    kit: "CONTENT-KIT"
    relativeURL: "media-atom"
    package: "https://token@github.com/applicaster/applicaster-developer-documentation.git"
    glob: "./src/applicaster-media-atom-feed.md"
  -
    title: "JS2Native"
    kit: "PLATFORM-KIT"
    relativeURL: "js2native"
    package: "https://token@github.com/applicaster/js2native.git"
    glob: "./docs/readme.md"
