---
# _______  ______    _______  ______   __   __  _______  _______  ___   _______  __    _
# |       ||    _ |  |       ||      | |  | |  ||       ||       ||   | |       ||  |  | |
# |    _  ||   | ||  |   _   ||  _    ||  | |  ||       ||_     _||   | |   _   ||   |_| |
# |   |_| ||   |_||_ |  | |  || | |   ||  |_|  ||       |  |   |  |   | |  | |  ||       |
# |    ___||    __  ||  |_|  || |_|   ||       ||      _|  |   |  |   | |  |_|  ||  _    |
# |   |    |   |  | ||       ||       ||       ||     |_   |   |  |   | |       || | |   |
# |___|    |___|  |_||_______||______| |_______||_______|  |___|  |___| |_______||_|  |__|
#
# Customer facing documentation - handle with care!
# List of RELEASES Docs packages.
#

  -
    title: "Media Atom v2.0.1"
    kit: "CONTENT-KIT"
    relativeURL: "media-atom-2"
    package: "https://token@github.com/applicaster/applicaster-developer-documentation.git#cc8482dcdb8074931a260263f0a0f531f5706066"
    glob: "./src/content/**"
  -
    title: "EPG Ingestion"
    kit: "CONTENT-KIT"
    relativeURL: "epg-ingestion"
    package: "https://token@github.com/applicaster/applicaster2.git#develop"
    glob: "./doc/features/epg-ingestion.md"
  -
    title: "JS2Native v1.1.0"
    kit: "PLATFORM-KIT"
    relativeURL: "js2native"
    package: "https://token@github.com/applicaster/js2native.git"
    glob: "./docs/readme.md"
  -
    title: "iOS Feed Integration"
    kit: "GAME-KIT"
    relativeURL: "ios-feed-integration"
    package: "https://token@github.com/applicaster/Applicaster-iOS-SDK-Lite-Static.wiki.git"
    glob: "./Feed-integration-instructions.md"
  -
    title: "Android Feed Integration"
    kit: "GAME-KIT"
    relativeURL: "android-feed-integration"
    package: "https://token@github.com/applicaster/feed-android-dist.git"
    glob: "./README.md"
  -
    title: "Android Applicaster SDK Integration"
    kit: "PLATFORM-KIT"
    relativeURL: "android-applicaster-sdk-integration"
    package: "https://token@github.com/applicaster/android-sdk-dist.git"
    glob: "./README.md"
  -
    title: "Media Atom v1.2.0"
    notes: "Please note that this document describes a previous API version."
    kit: "CONTENT-KIT"
    relativeURL: "media-atom"
    package: "https://token@github.com/applicaster/applicaster-developer-documentation.git#bf7021a7257cf241f313869c5bde238b5d1ae5ad"
    glob: "./src/content/**"
  -
    title: "Stars Public API v3"
    kit: "GAME-KIT"
    relativeURL: "stars-public-v3"
    package: "https://token@github.com/applicaster/stars.git#imporve-v3-docs"
    glob: "./doc/**"
