---
# List of INTERNAL Docs packages
  -
    title: "Developer Documentation"
    kit: "PLATFORM-KIT"
    relativeURL: "dev-doc-readme"
    package: "../docs/"
    glob: "./**"
  -
    title: "iOS Feed Integration"
    kit: "PLATFORM-KIT"
    relativeURL: "ios-feed-integration"
    package: "https://token@github.com/applicaster/Applicaster-iOS-SDK-Lite-Static.wiki.git"
    glob: "./Feed-integration-instructions.md"
  -
    title: "Question Service"
    kit: "GAME-KIT"
    relativeURL: "question-service"
    package: "../content/question-service/"
    glob: "./**"
